export type SampleFoodItem = {
  id: number;
  name: string;
  servingSize: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  saturatedFat: number;
  sodium: number;
  fiber: number;
  sugars: number;
  diningHall: string;
  station: string;
  recNumAndPort: string;
  cholesterol: number | null;
  transFat: number | null;
  ingredients: string | null;
  allergens: string | null;
  lastUpdated: Date;
};

const SAMPLE_TIMESTAMP = new Date("2026-01-01T00:00:00Z");

export const SAMPLE_FOODS: SampleFoodItem[] = [
  // South Campus - Breakfast
  {
    id: 1,
    name: "Scrambled Eggs",
    servingSize: "2 eggs",
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    saturatedFat: 3,
    sodium: 190,
    fiber: 0,
    sugars: 1,
    diningHall: "South Campus",
    station: "Breakfast Station",
    recNumAndPort: "eggs_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 2,
    name: "Whole Wheat Toast",
    servingSize: "2 slices",
    calories: 160,
    protein: 6,
    carbs: 28,
    fat: 2,
    saturatedFat: 0,
    sodium: 340,
    fiber: 4,
    sugars: 2,
    diningHall: "South Campus",
    station: "Breakfast Station",
    recNumAndPort: "toast_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 3,
    name: "Greek Yogurt",
    servingSize: "6 oz",
    calories: 100,
    protein: 17,
    carbs: 7,
    fat: 0,
    saturatedFat: 0,
    sodium: 75,
    fiber: 0,
    sugars: 4,
    diningHall: "South Campus",
    station: "Breakfast Station",
    recNumAndPort: "yogurt_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 4,
    name: "Oatmeal with Berries",
    servingSize: "1 cup",
    calories: 180,
    protein: 5,
    carbs: 34,
    fat: 3,
    saturatedFat: 1,
    sodium: 80,
    fiber: 5,
    sugars: 12,
    diningHall: "South Campus",
    station: "Breakfast Station",
    recNumAndPort: "oatmeal_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 5,
    name: "Bagel with Cream Cheese",
    servingSize: "1 bagel",
    calories: 290,
    protein: 11,
    carbs: 45,
    fat: 8,
    saturatedFat: 5,
    sodium: 560,
    fiber: 2,
    sugars: 4,
    diningHall: "South Campus",
    station: "Breakfast Station",
    recNumAndPort: "bagel_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // South Campus - Lunch
  {
    id: 6,
    name: "Grilled Chicken Breast",
    servingSize: "6 oz",
    calories: 280,
    protein: 53,
    carbs: 0,
    fat: 6,
    saturatedFat: 2,
    sodium: 75,
    fiber: 0,
    sugars: 0,
    diningHall: "South Campus",
    station: "Grill Works",
    recNumAndPort: "chicken_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 7,
    name: "Brown Rice",
    servingSize: "1 cup",
    calories: 215,
    protein: 5,
    carbs: 45,
    fat: 2,
    saturatedFat: 0,
    sodium: 10,
    fiber: 4,
    sugars: 1,
    diningHall: "South Campus",
    station: "Sides",
    recNumAndPort: "rice_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 8,
    name: "Roasted Vegetables",
    servingSize: "1.5 cups",
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 2,
    saturatedFat: 0,
    sodium: 180,
    fiber: 5,
    sugars: 8,
    diningHall: "South Campus",
    station: "Sides",
    recNumAndPort: "veggies_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 9,
    name: "Turkey Sandwich",
    servingSize: "1 sandwich",
    calories: 320,
    protein: 28,
    carbs: 35,
    fat: 8,
    saturatedFat: 2,
    sodium: 890,
    fiber: 2,
    sugars: 3,
    diningHall: "South Campus",
    station: "Sandwich Bar",
    recNumAndPort: "turkey_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 10,
    name: "Caesar Salad",
    servingSize: "2 cups",
    calories: 240,
    protein: 12,
    carbs: 12,
    fat: 16,
    saturatedFat: 4,
    sodium: 520,
    fiber: 2,
    sugars: 2,
    diningHall: "South Campus",
    station: "Salad Bar",
    recNumAndPort: "caesar_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // South Campus - Dinner
  {
    id: 11,
    name: "Pasta with Marinara",
    servingSize: "1.5 cups",
    calories: 350,
    protein: 14,
    carbs: 58,
    fat: 6,
    saturatedFat: 1,
    sodium: 680,
    fiber: 4,
    sugars: 8,
    diningHall: "South Campus",
    station: "Pasta Station",
    recNumAndPort: "pasta_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 12,
    name: "Baked Salmon",
    servingSize: "5 oz",
    calories: 280,
    protein: 35,
    carbs: 0,
    fat: 15,
    saturatedFat: 3,
    sodium: 75,
    fiber: 0,
    sugars: 0,
    diningHall: "South Campus",
    station: "Grill Works",
    recNumAndPort: "salmon_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 13,
    name: "Sweet Potato",
    servingSize: "1 medium",
    calories: 105,
    protein: 2,
    carbs: 24,
    fat: 0,
    saturatedFat: 0,
    sodium: 55,
    fiber: 4,
    sugars: 5,
    diningHall: "South Campus",
    station: "Sides",
    recNumAndPort: "sweetpotato_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 14,
    name: "Beef Tacos",
    servingSize: "2 tacos",
    calories: 420,
    protein: 24,
    carbs: 38,
    fat: 18,
    saturatedFat: 7,
    sodium: 720,
    fiber: 2,
    sugars: 2,
    diningHall: "South Campus",
    station: "Taco Bar",
    recNumAndPort: "tacos_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // Yahentamitsi - Breakfast
  {
    id: 15,
    name: "Pancakes with Syrup",
    servingSize: "2 pancakes",
    calories: 280,
    protein: 8,
    carbs: 54,
    fat: 4,
    saturatedFat: 1,
    sodium: 420,
    fiber: 1,
    sugars: 28,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Breakfast Station",
    recNumAndPort: "pancakes_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 16,
    name: "Bacon",
    servingSize: "3 slices",
    calories: 160,
    protein: 12,
    carbs: 0,
    fat: 12,
    saturatedFat: 4,
    sodium: 310,
    fiber: 0,
    sugars: 0,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Breakfast Station",
    recNumAndPort: "bacon_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 17,
    name: "Fresh Fruit Salad",
    servingSize: "1.5 cups",
    calories: 90,
    protein: 1,
    carbs: 23,
    fat: 0,
    saturatedFat: 0,
    sodium: 10,
    fiber: 3,
    sugars: 18,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Breakfast Station",
    recNumAndPort: "fruit_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // Yahentamitsi - Lunch
  {
    id: 18,
    name: "Veggie Burger",
    servingSize: "1 burger",
    calories: 240,
    protein: 12,
    carbs: 32,
    fat: 8,
    saturatedFat: 1,
    sodium: 580,
    fiber: 5,
    sugars: 2,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Grill Works",
    recNumAndPort: "vegburger_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 19,
    name: "Hummus and Vegetables",
    servingSize: "1 cup",
    calories: 180,
    protein: 6,
    carbs: 18,
    fat: 9,
    saturatedFat: 1,
    sodium: 380,
    fiber: 5,
    sugars: 2,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Salad Bar",
    recNumAndPort: "hummus_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 20,
    name: "Quinoa Bowl",
    servingSize: "1.5 cups",
    calories: 320,
    protein: 12,
    carbs: 48,
    fat: 8,
    saturatedFat: 1,
    sodium: 420,
    fiber: 8,
    sugars: 3,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Grain Bar",
    recNumAndPort: "quinoa_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // Yahentamitsi - Dinner
  {
    id: 21,
    name: "Stir Fry with Tofu",
    servingSize: "1.5 cups",
    calories: 280,
    protein: 18,
    carbs: 28,
    fat: 12,
    saturatedFat: 2,
    sodium: 640,
    fiber: 4,
    sugars: 6,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Wok Station",
    recNumAndPort: "stirfry_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 22,
    name: "Vegetable Fried Rice",
    servingSize: "1.5 cups",
    calories: 240,
    protein: 8,
    carbs: 38,
    fat: 6,
    saturatedFat: 1,
    sodium: 520,
    fiber: 3,
    sugars: 2,
    diningHall: "Yahentamitsi Dining Hall",
    station: "Wok Station",
    recNumAndPort: "friedrice_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // 251 North - Breakfast
  {
    id: 23,
    name: "Breakfast Burrito",
    servingSize: "1 burrito",
    calories: 380,
    protein: 16,
    carbs: 42,
    fat: 16,
    saturatedFat: 6,
    sodium: 720,
    fiber: 3,
    sugars: 2,
    diningHall: "251 North",
    station: "Breakfast Station",
    recNumAndPort: "burrito_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 24,
    name: "Smoothie Bowl",
    servingSize: "1 bowl",
    calories: 280,
    protein: 10,
    carbs: 48,
    fat: 5,
    saturatedFat: 1,
    sodium: 80,
    fiber: 6,
    sugars: 24,
    diningHall: "251 North",
    station: "Breakfast Station",
    recNumAndPort: "smoothie_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // 251 North - Lunch
  {
    id: 25,
    name: "Pulled Pork Sandwich",
    servingSize: "1 sandwich",
    calories: 450,
    protein: 32,
    carbs: 38,
    fat: 18,
    saturatedFat: 6,
    sodium: 980,
    fiber: 2,
    sugars: 8,
    diningHall: "251 North",
    station: "Sandwich Bar",
    recNumAndPort: "pork_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 26,
    name: "Coleslaw",
    servingSize: "1 cup",
    calories: 150,
    protein: 2,
    carbs: 12,
    fat: 10,
    saturatedFat: 1,
    sodium: 420,
    fiber: 2,
    sugars: 8,
    diningHall: "251 North",
    station: "Sides",
    recNumAndPort: "coleslaw_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  // 251 North - Dinner
  {
    id: 27,
    name: "Pizza Slice",
    servingSize: "1 slice",
    calories: 280,
    protein: 14,
    carbs: 36,
    fat: 10,
    saturatedFat: 4,
    sodium: 640,
    fiber: 2,
    sugars: 2,
    diningHall: "251 North",
    station: "Pizza Station",
    recNumAndPort: "pizza_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
  {
    id: 28,
    name: "Garlic Bread",
    servingSize: "2 pieces",
    calories: 180,
    protein: 4,
    carbs: 22,
    fat: 8,
    saturatedFat: 3,
    sodium: 380,
    fiber: 1,
    sugars: 1,
    diningHall: "251 North",
    station: "Sides",
    recNumAndPort: "garlic_001",
    cholesterol: null,
    transFat: null,
    ingredients: "Sample food item",
    allergens: "[]",
    lastUpdated: SAMPLE_TIMESTAMP,
  },
];
